### ISSUE TITLE
Build failure against the ffmpeg git repo

### ISSUE THREAD

**Issue by orbea** [DeaDBeeF-Player/deadbeef#2609]
### Steps to reproduce the problem

1. Build deadbeef against the ffmpeg git repo.

### What's going on? Describe the problem in as much detail as possible.
```
rdlibtool --tag=CC --mode=compile clang -DHAVE_CONFIG_H -I. -I../.. -O2 -fPIC -D_GNU_SOURCE -D__EXTENSIONS__ -DLIBDIR="/usr/lib64" -DPREFIX="/usr" -DDOCDIR="/usr/doc/deadbeef-2021.05.23_44806e4" -DDDB_WARN_DEPRECATED=1 -std=c99 -O2 -fPIC -D_GNU_SOURCE -D__EXTENSIONS__ -DLIBDIR="/usr/lib64" -DPREFIX="/usr" -DDOCDIR="/usr/doc/deadbeef-2021.05.23_44806e4" -DDDB_WARN_DEPRECATED=1 -c -o ffmpeg.lo ffmpeg.c

rdlibtool: lconf: {.name="libtool"}.
rdlibtool: fdcwd: {.fdcwd=AT_FDCWD, .realpath="/tmp/SBo/deadbeef/plugins/ffmpeg"}.
rdlibtool: lconf: fstatat(AT_FDCWD,".",...) = 0 {.st_dev = 34, .st_ino = 32783}.
rdlibtool: lconf: openat(AT_FDCWD,"libtool",O_RDONLY,0) = -1 [ENOENT].
rdlibtool: lconf: openat(AT_FDCWD,"../",O_DIRECTORY,0) = 3.
rdlibtool: lconf: fstat(3,...) = 0 {.st_dev = 34, .st_ino = 31630}.
rdlibtool: lconf: openat(3,"libtool",O_RDONLY,0) = -1 [ENOENT].
rdlibtool: lconf: openat(3,"../",O_DIRECTORY,0) = 4.
rdlibtool: lconf: fstat(4,...) = 0 {.st_dev = 34, .st_ino = 31271}.
rdlibtool: lconf: openat(4,"libtool",O_RDONLY,0) = 3.
rdlibtool: lconf: found "/tmp/SBo/deadbeef/libtool".
rdlibtool: compile: clang -DHAVE_CONFIG_H -I. -I../.. -O2 -fPIC -D_GNU_SOURCE -D__EXTENSIONS__ -DLIBDIR="/usr/lib64" -DPREFIX="/usr" -DDOCDIR="/usr/doc/deadbeef-2021.05.23_44806e4" -DDDB_WARN_DEPRECATED=1 -std=c99 -O2 -fPIC -D_GNU_SOURCE -D__EXTENSIONS__ -DLIBDIR="/usr/lib64" -DPREFIX="/usr" -DDOCDIR="/usr/doc/deadbeef-2021.05.23_44806e4" -DDDB_WARN_DEPRECATED=1 -c ffmpeg.c -DPIC -fPIC -o .libs/ffmpeg.o
ffmpeg.c:181:45: error: no member named 'codec' in 'struct AVStream'
        info->ctx = info->fctx->streams[i]->codec;
                    ~~~~~~~~~~~~~~~~~~~~~~  ^
ffmpeg.c:184:25: warning: assigning to 'AVCodec *' (aka 'struct AVCodec *') from 'const AVCodec *' (aka 'const struct AVCodec *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
            info->codec = avcodec_find_decoder (info->ctx->codec_id);
                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ffmpeg.c:328:19: warning: implicit declaration of function 'avcodec_decode_audio4' is invalid in C99 [-Wimplicit-function-declaration]
            len = avcodec_decode_audio4(info->ctx, info->frame, &got_frame, &info->pkt);
                  ^
ffmpeg.c:690:33: error: no member named 'codec' in 'struct AVStream'
        ctx = fctx->streams[i]->codec;
              ~~~~~~~~~~~~~~~~  ^
ffmpeg.c:698:19: warning: assigning to 'AVCodec *' (aka 'struct AVCodec *') from 'const AVCodec *' (aka 'const struct AVCodec *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
            codec = avcodec_find_decoder(ctx->codec_id);
                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ffmpeg.c:760:42: warning: format specifies type 'long long' but the argument has type 'int64_t' (aka 'long') [-Wformat]
        snprintf (s, sizeof (s), "%lld", fsize);
                                  ~~~~   ^~~~~
                                  %ld
ffmpeg.c:855:24: warning: implicit declaration of function 'av_iformat_next' is invalid in C99 [-Wimplicit-function-declaration]
        while ((ifmt = av_iformat_next(ifmt))) {
                       ^
ffmpeg.c:855:22: warning: incompatible integer to pointer conversion assigning to 'AVInputFormat *' (aka 'struct AVInputFormat *') from 'int' [-Wint-conversion]
        while ((ifmt = av_iformat_next(ifmt))) {
                     ^ ~~~~~~~~~~~~~~~~~~~~~
ffmpeg.c:905:5: warning: implicit declaration of function 'av_register_all' is invalid in C99 [-Wimplicit-function-declaration]
    av_register_all ();
    ^
ffmpeg.c:956:33: error: no member named 'codec' in 'struct AVStream'
        ctx = fctx->streams[i]->codec;
              ~~~~~~~~~~~~~~~~  ^
ffmpeg.c:959:19: warning: assigning to 'AVCodec *' (aka 'struct AVCodec *') from 'const AVCodec *' (aka 'const struct AVCodec *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
            codec = avcodec_find_decoder(ctx->codec_id);
                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8 warnings and 3 errors generated.
rdlibtool: error logged in slbt_exec_compile(), line 209: Success.
make[2]: *** [Makefile:560: ffmpeg.lo] Error 2
make[2]: Leaving directory '/tmp/SBo/deadbeef/plugins/ffmpeg'
make[1]: *** [Makefile:835: all-recursive] Error 1
make[1]: Leaving directory '/tmp/SBo/deadbeef'
make: *** [Makefile:621: all] Error 2
```

### Information about the software:

Deadbeef version: https://github.com/DeaDBeeF-Player/deadbeef/commit/44806e45906bd03e5d3ace464f0a0cd228eb4577
FFmpeg version: https://github.com/FFmpeg/FFmpeg/commit/4c705a2775afca7eadc40835bfaafb29a9c5c38a
OS: `Slackware64-current`

**Comment by stefson** [comment]
I'll try to reproduce and maybe bisect if needed to.

**Comment by Alexey-Yakovenko** [comment]
It is most likely caused by ffmpeg removing some deprecated symbols, which are currently used by deadbeef's ffmpeg plugin -- so there's really not much to bisect, but instead the plugin needs to be updated to use the new(er) APIs.

**Comment by Alexey-Yakovenko** [comment]
FYI: The current ffmpeg plugin builds with ffmpeg-4.4, but to build against a newer version requires changing the code.
If someone decided to implement support for ffmpeg>4.4, please consider removing some code that implements support for super old ffmpeg versions like 0.10.

**Comment by Alexey-Yakovenko** [comment]
I partially fixed the code to use fewer deprecated APIs, but the usage of the avcodec_decode_audio4 is not fixed yet

**Comment by Alexey-Yakovenko** [comment]
Ok I went all the way and fixed all things which seemed deprecated, including the avcodec_decode_audio4.
I haven't tested with ffmpeg from git though, but the code still builds and works with 4.4

**Comment by orbea** [comment]
Thanks! It builds and works on my end with a ffmpeg that was built a little over a week ago.
