### ISSUE TITLE
Doesn't build with ffmpeg 0.11

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#714]
Original [issue 812](https://code.google.com/p/ddb/issues/detail?id=812) created by Alexey-Yakovenko on 2012-05-29T12:48:50.000Z:

0.5.4 doens't build under Debian unstable with ffmpeg 0.11

See below the build output.

Christian

ffmpeg.c: In function 'ffmpeg_read_metadata_internal':
ffmpeg.c:457:5: error: unknown type name 'AVMetadata'
ffmpeg.c:457:22: warning: initialization from incompatible pointer type [enabled by default]
ffmpeg.c:460:9: error: unknown type name 'AVMetadataTag'
ffmpeg.c:462:13: warning: implicit declaration of function 'av_metadata_get' [-Wimplicit-function-declaration]
ffmpeg.c:462:53: error: 'AV_METADATA_DONT_STRDUP_KEY' undeclared (first use in this function)
ffmpeg.c:462:53: note: each undeclared identifier is reported only once for each function it appears in
ffmpeg.c:462:83: error: 'AV_METADATA_DONT_STRDUP_VAL' undeclared (first use in this function)
ffmpeg.c:464:60: error: request for member 'value' in something not a structure or union
ffmpeg.c: In function 'ffmpeg_insert':
ffmpeg.c:504:5: warning: 'av_find_stream_info' is deprecated (declared at /usr/include/libavformat/avformat.h:1357) [-Wdeprecated-declarations]
ffmpeg.c:526:9: warning: 'av_close_input_file' is deprecated (declared at /usr/include/libavformat/avformat.h:1533) [-Wdeprecated-declarations]
ffmpeg.c:532:5: warning: 'avcodec_open' is deprecated (declared at /usr/include/libavcodec/avcodec.h:3380) [-Wdeprecated-declarations]
ffmpeg.c:534:9: warning: 'av_close_input_file' is deprecated (declared at /usr/include/libavformat/avformat.h:1533) [-Wdeprecated-declarations]
ffmpeg.c:588:5: warning: 'av_close_input_file' is deprecated (declared at /usr/include/libavformat/avformat.h:1533) [-Wdeprecated-declarations]
ffmpeg.c: At top level:
ffmpeg.c:605:17: error: unknown type name 'URLContext'
ffmpeg.c:630:17: error: unknown type name 'URLContext'
ffmpeg.c:638:18: error: unknown type name 'URLContext'
ffmpeg.c:644:17: error: unknown type name 'URLContext'
ffmpeg.c:662:18: error: unknown type name 'URLContext'
ffmpeg.c:669:1: error: unknown type name 'URLProtocol'
ffmpeg.c:670:5: error: field name not in record or union initializer
ffmpeg.c:670:5: error: (near initialization for 'vfswrapper')
ffmpeg.c:670:5: warning: initialization makes integer from pointer without a cast [enabled by default]
ffmpeg.c:670:5: warning: (near initialization for 'vfswrapper') [enabled by default]
ffmpeg.c:671:5: error: field name not in record or union initializer
ffmpeg.c:671:5: error: (near initialization for 'vfswrapper')
ffmpeg.c:671:17: error: 'ffmpeg_vfs_open' undeclared here (not in a function)
ffmpeg.c:671:5: warning: excess elements in scalar initializer [enabled by default]
ffmpeg.c:671:5: warning: (near initialization for 'vfswrapper') [enabled by default]
ffmpeg.c:672:5: error: field name not in record or union initializer
ffmpeg.c:672:5: error: (near initialization for 'vfswrapper')
ffmpeg.c:672:17: error: 'ffmpeg_vfs_read' undeclared here (not in a function)
ffmpeg.c:672:5: warning: excess elements in scalar initializer [enabled by default]
ffmpeg.c:672:5: warning: (near initialization for 'vfswrapper') [enabled by default]
ffmpeg.c:673:5: error: field name not in record or union initializer
ffmpeg.c:673:5: error: (near initialization for 'vfswrapper')
ffmpeg.c:673:18: error: 'ffmpeg_vfs_write' undeclared here (not in a function)
ffmpeg.c:673:5: warning: excess elements in scalar initializer [enabled by default]
ffmpeg.c:673:5: warning: (near initialization for 'vfswrapper') [enabled by default]
ffmpeg.c:674:5: error: field name not in record or union initializer
ffmpeg.c:674:5: error: (near initialization for 'vfswrapper')
ffmpeg.c:674:17: error: 'ffmpeg_vfs_seek' undeclared here (not in a function)
ffmpeg.c:674:5: warning: excess elements in scalar initializer [enabled by default]
ffmpeg.c:674:5: warning: (near initialization for 'vfswrapper') [enabled by default]
ffmpeg.c:675:5: error: field name not in record or union initializer
ffmpeg.c:675:5: error: (near initialization for 'vfswrapper')
ffmpeg.c:675:18: error: 'ffmpeg_vfs_close' undeclared here (not in a function)
